### ISSUE TITLE
Legenda dos vídeos

### ISSUE THREAD

**Issue by henricavalcante** [cerebrobr/cerebro#10]
Atualmente está sendo usado alguma ferramenta para a legendagem dos vídeos? Pensei em criarmos um time no amara.org para as legendas dos vídeos. Caso a idéia seja válida posso criar o time e um pull request aqui dos passos que devem ser seguidos para a criação das legendas.

**Comment by vitorbritto** [comment]
@henricavalcante movendo a sugestão para esta [issue](https://github.com/cerebrobr/cerebro/issues/2). Obrigado. =]
