### ISSUE TITLE
Nova seção de meetups

### ISSUE THREAD

**Issue by pedropolisenso** [cerebrobr/cerebro#12]
Fala pessoal, tudo certo? Então. Analisando a aplicação online do projeto Cerebro, vi que poderiamos acrescentar na seção **ESTRUTURA** o link para meetups. Facilita o acesso para quem visitar o website

**Comment by pedropolisenso** [comment]
Pull Request Done! :+1:

**Comment by rodneidesign** [comment]
:+1:
