### ISSUE TITLE
Aprovação para contribuição

### ISSUE THREAD

**Issue by nicholasess** [cerebrobr/cerebro#16]
Olá senhores.
Com o inicio do ano e ausência de muitos, acredito que não haja tanta necessidade que todos concordem com adição de itens nos repositórios através das PRs ou algo similar, tendo em vista que isso é uma comunidade.
Acredito também que, mesmo que esteja no meio do ano, muitos não vão participar, por dar importância a outras coisas.
Então ter duas pessoas pra mais, a atualização pode ser feita, mas dentro das regras do cerebro.
O que acham?

@cerebrobr/colaboradores @cerebrobr/editores @vitorbritto

**Comment by pedropolisenso** [comment]
@nicholasess confesso que não entendi muito bem a ideia sugerida.

**Comment by nicholasess** [comment]
e agora?

**Comment by LFeh** [comment]
Não entendi, hehe

**Comment by vitorbritto** [comment]
A intenção é agilizar o processo. Havendo a aprovação de um _pull request_ por duas pessoas (ou mais). Sem a necessidade de aguardar a aprovação de pessoa A, B ou C. Temos muitos colaboradores "cadastrados", mas alguns não participam ativamente. 

Eu concordo, se for essa a questão. :neckbeard: 

O mais importante é que o _commit_ e _pull request_ sejam feitos de acordo com nossos padrões. Qualquer eventualidade, podemos corrigir depois.

**Comment by nicholasess** [comment]
É essa questão mesmo

**Comment by vitorbritto** [comment]
Por mim, está ok! :+1:

**Comment by pedropolisenso** [comment]
Humm saquei a ideia, muito bom essa sugestão. Eu não aprovo nada, mas por mim também está ok :+1: Rsrs

**Comment by hugobessaa** [comment]
:+1:
Em ter, 10 de fev de 2015 às 12:50, Vitor Britto <notifications@github.com>
escreveu:

**Comment by fdaciuk** [comment]
Acho massa! Pra facilitar ainda mais, a pessoa que for conferir se o commit está certo, comenta com um "+1". Se tiver 2 "+1", já pode ser feito o merge.

Se tiver alguma coisa errada, comente direto no código do commit (clicando no "+" que aparece no lado esquerdo da linha), colocando "-1".

Assim que tiver resolvido os problemas do commit, e tendo somados os pontos, 2 "+1", já pode ser feito o merge. O que acham?

**Comment by nicholasess** [comment]
Muito bom, já estou adotando essa prática.
+1 na sugestão do @fdaciuk

**Comment by pedropolisenso** [comment]
Boa @fdaciuk isso agiliza!

**Comment by oliveiraev** [comment]
> Assim que tiver resolvido os problemas do commit, e tendo somados os pontos, 2 "+1", já pode ser feito o merge. O que acham?

:+1:

**Comment by pedropolisenso** [comment]
Sim @oliveiraev o @fdaciuk chegou a sugerir isso também!

**Comment by fdaciuk** [comment]
Ele só fez citação do que eu escrevi @pedropolisenso xD

**Comment by pedropolisenso** [comment]
Putz pode crer, to olhando aqui e programando nem percebi =)

**Comment by vitorbritto** [comment]
+1 ou :+1:
-1 ou :-1:

**Comment by fdaciuk** [comment]
> +1 ou :+1: 
> -1 ou :-1: 

Yep!

**Comment by rodneidesign** [comment]
:+1:

**Comment by IAMFELIPESOUZA** [comment]
+1 @fdaciuk

**Comment by LFeh** [comment]
+1 @fdaciuk =)

**Comment by thulioph** [comment]
Também acho interessante que a turma leia mais a documentação porque quem fez, fez com carinho, atenção, tudo bem explicado.. Eu tento ser ativo aqui mas as vezes passa despercebido, lá na doc. tem informando pra pessoa convocar os editores/ajudantes/jah/alá quando enviar um pr mas ninguém faz isso.

Então já que falei demais +1 :+1: @fdaciuk o/

**Comment by danilovaz** [comment]
:+1: @fdaciuk nós fazemos esse esquema no repo do io.js e funciona muito bem.

**Comment by nicholasess** [comment]
Obrigado a todos pela discussão!

**Comment by fdaciuk** [comment]
Essa informação só precisaria ficar registrada em algum lugar, eu acho. Talvez deixar essa issue marcada como TO DO para colocar essa informação no README.

Assim, qualquer pessoa pode conferir e dar **+1**. Só deixar claro que esse **+1** que está sendo dado, é porque ela conferiu o _pull request_, e está de acordo com o padrão. Tipo, vai deixar o voto de **+1** valendo o **** mesmo, haha! xD

**Comment by nicholasess** [comment]
E aonde pode ficar esse TO DO?
Não existe regras para os colaboradores e editores seguirem, é só para quem está de fora.
De fora pra dentro, não de dentro pra fora.

**Comment by nicholasess** [comment]
Pensei em adicionar no arquivo central do [cerebro](https://github.com/cerebrobr/cerebro)

**Sobre Colaboradores e Editores**

Quando receberem _pull request_ e o mesmo estiver dentro das regras de contribuição do **cerebro** para o repositório em questão. O _pull request_ será aceito, somente se houverem mais de uma aprovação por parte dos **colaboradores** e **editores**. A pessoa que for conferir se o commit está certo, comenta com um "+1". Se tiver 2 "+1", já pode ser feito o merge.

Se tiver alguma coisa errada, comente direto no código do commit (clicando no "+" que aparece no lado esquerdo da linha), colocando "-1".

Assim que tiver resolvido os problemas do commit, e tendo somados os pontos, 2 "+1", já pode ser feito o merge.

**Comment by fdaciuk** [comment]
Acho uma boa! Só tem que fazer um _clean code_ nesse texto ae :P
Escrevi só jogando a ideia, tem muita repetição xD

**Comment by thulioph** [comment]
Concordo  com o @fdaciuk, da uma limpada na repetição e põe nesse local proposto mesmo.
